export const LIFECYCLE_STAGES = [
  { id: 'enquiry',              label: 'Enquiry',               icon: '🔍', short: 'ENQ' },
  { id: 'tender-review',        label: 'Tender Review',         icon: '📋', short: 'TNR' },
  { id: 'tender-submission',    label: 'Tender Submission',     icon: '📤', short: 'SUB' },
  { id: 'contract-award',       label: 'Contract Award',        icon: '🏆', short: 'AWD' },
  { id: 'contract-review',      label: 'Contract Review',       icon: '⚖️', short: 'CTR' },
  { id: 'project-setup',        label: 'Project Setup',         icon: '⚙️', short: 'SET' },
  { id: 'mobilisation',         label: 'Mobilisation',          icon: '🚧', short: 'MOB' },
  { id: 'live-delivery',        label: 'Live Delivery',         icon: '🏗️', short: 'LIV' },
  { id: 'payment-applications', label: 'Payment Applications',  icon: '💷', short: 'PAY' },
  { id: 'variations',           label: 'Variations',            icon: '📝', short: 'VAR' },
  { id: 'meetings-governance',  label: 'Meetings & Governance', icon: '👥', short: 'MTG' },
  { id: 'disputes-claims',      label: 'Disputes & Claims',     icon: '⚠️', short: 'DIS' },
  { id: 'handover',             label: 'Handover',              icon: '🔑', short: 'HOV' },
  { id: 'final-account',        label: 'Final Account',         icon: '📊', short: 'FAC' },
  { id: 'lessons-learned',      label: 'Lessons Learned',       icon: '📚', short: 'ARC' },
];

export const AGENTS = [
  { id: 'qs-cost',                name: 'QS / Cost',                icon: '💷', colour: '#00ffaa' },
  { id: 'contract-law',           name: 'Contract & Law',           icon: '⚖️', colour: '#00d4ff' },
  { id: 'dispute-claims',         name: 'Dispute & Claims',         icon: '⚠️', colour: '#ff4466' },
  { id: 'programme-delay',        name: 'Programme / Delay',        icon: '📅', colour: '#ffcc00' },
  { id: 'risk',                   name: 'Risk',                     icon: '🎯', colour: '#ff6b35' },
  { id: 'technical-review',       name: 'Technical Review',         icon: '🔧', colour: '#8888ff' },
  { id: 'site-reporting',         name: 'Site Reporting',           icon: '📋', colour: '#00d4ff' },
  { id: 'compliance-hs',          name: 'Compliance / H&S',         icon: '🦺', colour: '#ffb347' },
  { id: 'asbestos',               name: 'Asbestos',                 icon: '☢️', colour: '#ff6666' },
  { id: 'demolition',             name: 'Demolition',               icon: '🏚️', colour: '#cc8844' },
  { id: 'civil-engineering',      name: 'Civil Engineering',        icon: '🏗️', colour: '#44bbcc' },
  { id: 'structural',             name: 'Structural',               icon: '🏛️', colour: '#9988cc' },
  { id: 'temporary-works',        name: 'Temporary Works',          icon: '🔩', colour: '#ccaa44' },
  { id: 'geotechnical',           name: 'Geotechnical',             icon: '⛏️', colour: '#886644' },
  { id: 'remediation',            name: 'Remediation',              icon: '🌱', colour: '#44cc88' },
  { id: 'plant-equipment',        name: 'Plant & Equipment',        icon: '🚜', colour: '#ffaa22' },
  { id: 'tender-preconstruction', name: 'Tender / Pre-Con',         icon: '📐', colour: '#88aaff' },
  { id: 'document-control',       name: 'Document Control',         icon: '📁', colour: '#aaaaff' },
  { id: 'meeting-chair',          name: 'Meeting Chair',            icon: '👔', colour: '#cc88ff' },
  { id: 'payment-evidence',       name: 'Payment Evidence',         icon: '📸', colour: '#44ffcc' },
  { id: 'handover-closeout',      name: 'Handover / Close-Out',     icon: '🔑', colour: '#ffee44' },
  { id: 'labour-productivity',    name: 'Labour / Productivity',    icon: '👷', colour: '#ff8888' },
  { id: 'email-correspondence',   name: 'Email & Correspondence',   icon: '✉️', colour: '#88ccff' },
  { id: 'asta-programme',         name: 'Asta Programme',           icon: '📊', colour: '#ffcc88' },
  { id: 'director-intelligence',  name: 'Director Intelligence',    icon: '🎯', colour: '#ff6688' },
];

export const STATE_COLOURS = {
  idle:     { primary: '#00d4ff', glow: 'rgba(0,212,255,0.22)',  ring: 'rgba(0,212,255,0.5)'  },
  listening:{ primary: '#00ff88', glow: 'rgba(0,255,136,0.22)',  ring: 'rgba(0,255,136,0.5)'  },
  thinking: { primary: '#ffcc00', glow: 'rgba(255,204,0,0.22)',  ring: 'rgba(255,204,0,0.5)'  },
  speaking: { primary: '#bf80ff', glow: 'rgba(191,128,255,0.22)',ring: 'rgba(191,128,255,0.5)'},
  agents:   { primary: '#ff6b35', glow: 'rgba(255,107,53,0.22)', ring: 'rgba(255,107,53,0.5)' },
  meeting:  { primary: '#ff4466', glow: 'rgba(255,68,102,0.22)', ring: 'rgba(255,68,102,0.5)' },
};
